### ISSUE TITLE
구글 api 실행과정중 오류

### ISSUE THREAD

**Issue by cats0713** [wjrmffldrhrl/UleungCare#12]
## 첫번째 오류 [ pushtotalk ]
- undefined symbol: __atomic_exchange_8
<pre><code>
(venv) ➜  google_home$ googlesamples-assistant-pushtotalk --project-id <removed>  --device-model-id <removed>                    
Traceback (most recent call last):
  File "/home/pi/google_home/venv/bin/googlesamples-assistant-pushtotalk", line 6, in <module>
    from googlesamples.assistant.grpc.pushtotalk import main
  File "/home/pi/google_home/venv/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 28, in <module>
    import grpc
  File "/home/pi/google_home/venv/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /home/pi/google_home/venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_exchange_8
</code></pre>

# 두번째 오류 [ hotword ]
- 세그먼트 분할오류

**Comment by cats0713** [comment]
gRPC 버젼을 1.23으로 다운 그레이드하면 문제가 해결된다고 나와있지만 어떻게 다운그레이드를 해야하는지 찾지 못했다.

**Comment by cats0713** [comment]
첫번째 오류인  undefined symbol: __atomic_exchange_8 이것은 
sudo pip install grpcio==1.23.0 
위의 명령어를 사용하여 gRPC 버젼을 1.23으로 다운 그레이드하였다.

**Comment by cats0713** [comment]
<pre><code>
INFO:root:Connecting to embeddedassistant.googleapis.com
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->playback, outParams, self->primeBuffers, hwParamsPlayback, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2722
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 10, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 351, in main
    flush_size=audio_flush_size
  File "/home/pi/env/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env/lib/python3.7/site-packages/sounddevice.py", line 1345, in __init__
    **_remove_self(locals()))
  File "/home/pi/env/lib/python3.7/site-packages/sounddevice.py", line 861, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/env/lib/python3.7/site-packages/sounddevice.py", line 2653, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]
</code></pre>

undefined symbol: __atomic_exchange_8 문제를 해결하고 다시 시도해보니 이런 오류가 발생하였다.
(pushtotalk)

**Comment by wjrmffldrhrl** [comment]
API 적용 과정에 많은 오류가 발생되는 것으로 보입니다.  
아무래도 이번에 처음 시도해보는 과정이라 많은 어려움이 있습니다.  

API적용 부분에 인원을 조금 더 배치하겠습니다.

**Comment by cats0713** [comment]
초기화하고 여러번 반복하다보니 과정중에 마이크를 설정하는 과정이 빠져서 오류를 초래했다.

**Comment by cats0713** [comment]
googlesamples-assistant-pushtotalk  --lang ko-KR

위의 명령어를 사용하면 한글로 pushtotalk 사용할수있다.
